copyright = "@ {year} {title}"
baseURL = "https://pyre-project.org/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
    [languages.en]
        title = "Pyre Project"
        languageName = "English"
        contentDir = "content/en/"
        weight = 10

    [languages.es]
        title = "Proyecto de Pira"
        languageName = "Español"
        contentDir = "content/es/"
        weight = 20